# Generated by Django 4.0.4 on 2022-08-20 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_food_orderfood_rating_table_tableorder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='rating_food',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='food',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rating',
        ),
        migrations.AddField(
            model_name='food',
            name='rating',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.rating'),
        ),
        migrations.AlterField(
            model_name='tableorder',
            name='status',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
