# Generated by Django 4.0.4 on 2022-08-27 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_food_rating_food_remove_rating_food_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Rating', 'verbose_name_plural': 'Ratings'},
        ),
        migrations.RemoveField(
            model_name='food',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='count',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='total',
        ),
        migrations.AddField(
            model_name='rating',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food', to='main.food'),
        ),
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='main.client'),
        ),
    ]
