# Generated by Django 4.0.4 on 2022-08-27 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_rating_options_remove_food_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('client', 'food')},
        ),
    ]
