# Generated by Django 4.0.4 on 2022-08-27 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_rating_options_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
    ]
