# Generated by Django 4.0.4 on 2022-08-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
