# Generated by Django 4.0.4 on 2022-08-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_food_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='rating',
            new_name='rate',
        ),
    ]
